### ISSUE TITLE
有没有非替换man手册的离线版本

### ISSUE THREAD

**Issue by CHN-STUDENT** [man-pages-zh/manpages-zh#11]
这是个不错的项目，我想下个离线版备用使用。
但是离线版是从源码编译，会替换系统自带的`man`，我想保留系统的自带`man`指令，作为对照使用。
我可能想要一个离线的html的版本，不知道你们是否能提供呢？
谢谢。

**Comment by hosiet** [comment]
首先，安装本项目不会替换系统 man 手册页，因 man 命令会根据你的系统语言对应环境决定显示何种语言的手册页，并且在对应手册页不存在时进行回退。安装后如需在中文系统上显示原英文手册页，请临时切换 locale 相关环境变量即可。

另外，html 页面暂无计划，但是使用 groff 可以方便地进行生成，和 manpages.debian.org 的原理相同。如有兴趣，欢迎提交 pull request。
