### ISSUE TITLE
No manual entry for ls

### ISSUE THREAD

**Issue by Crazy-dog-egg** [man-pages-zh/manpages-zh#15]
使用cman ls时报错:No manual entry for ls
man ls没有问题

**Comment by hosiet** [comment]
cman 是什么命令？感觉以前并没有听说过

**Comment by hosiet** [comment]
当代的 Linux 发行版无论系统语言为何应该全部都是 UTF-8 编码的，因此无论任何时候使用 cman 这个命令都是没有必要的，现在的 manpages-zh 也不提供 cman 命令。
