### ISSUE TITLE
如何卸载

### ISSUE THREAD

**Issue by liu-tongxue** [man-pages-zh/manpages-zh#16]

**Comment by Hill-98** [comment]
你如果是用发行版的包管理工具安装的，使用包管理工具卸载对应的包即可，比如 Debian/Ubuntu 执行`sudo apt remove manpages-zh`卸载。

**Comment by hosiet** [comment]
如果使用 Autotools 标准的 `make install` 安装，请在同样位置调用 `make uninstall` 进行卸载。如果使用 Linux 发行版所提供的软件包安装，请使用对应发行版的软件包管理工具进行卸载。

在最糟糕的情况下，可以浏览 `/usr/share/man/zh_{CN,TW}/` 并找到不需要的手册页手动删除。
