### ISSUE TITLE
Man-pages-zh_cn and man-pages-zh_tw conflict

### ISSUE THREAD

**Issue by stevenfang1997** [man-pages-zh/manpages-zh#19]
I'm on Manjaro KDE.

I used to have both man-pages-zh_cn and man-pages-zh_tw installed. After selecting update both to the latest version (10.05.2020), I saw this error in Pamac:

```
conflicting files:
/usr/share/doc/manpages-zh/COPYRIGHT exists in both man-pages-zh_cn and man-pages-zh_tw
```

I think right now man-pages-zh_can and man-pages-zh_two are conflicting each other. I have to remove one of these packages to proceed the update.

Can you please fix that? Thank you!

**Comment by hosiet** [comment]
@felixonmars What do you think would be a good solution?

**Comment by felixonmars** [comment]
I think I fixed it right after the broken release. Perhaps OP should contact Manjaro to sync the fixed version.

**Comment by stevenfang1997** [comment]
Thanks for your replies. The issue is fixed after updating to the latest Manjaro version. I guess it was more likely the problem of Manjaro/Arch.

**Comment by hosiet** [comment]
I see `https://discover.manjaro.org/packages/man-pages-zh_cn` still mentions the old version but anyway it has been fixed in Arch upstream. It's ok as long as you don't encounter this issue anymore.
