### ISSUE TITLE
关于缺少pr命令的问题

### ISSUE THREAD

**Issue by adminlinzi** [man-pages-zh/manpages-zh#21]
pr命令查询不到。
使用系统原有man是可以查到。

# 其他
README文件并未给出centos环境安装的方式，只给了debian和arch的。在centos7环境中，v152版本可以正常编译使用。v1621版本编译出现多种报错。v1621版本是测试版吗。

**Comment by hosiet** [comment]
pr 命令的中文翻译尚未完成，因此暂时无法查询到。

CentOS 的使用/安装问题请单独开 issue 报告，并提供出现错误的屏幕截图等方便分析问题的信息。
