### ISSUE TITLE
我在m1芯片上的mac上成功使用了双语的linux-manpage

### ISSUE THREAD

**Issue by Kaiyan-Zhang** [man-pages-zh/manpages-zh#22]
- 机器：macbook pro m1
- 系统版本：Big Sur 11.2
- 效果：成功使用中文不乱码（手动copy paste同时安装最新版的groff）
![v2-4255215e66c4b5791bbfa6a41b9667b4_r](https://user-images.githubusercontent.com/61637391/107150890-ff0f3980-699a-11eb-9900-a4e6e3a82ff3.jpg)

我提出这个Issue是为了让更多的用m1的mac用户不要踩我踩过的坑，另一方面也是证明在mac上使用linux中文manpage的可行性。
我在m1芯片上的mac上成功使用了双语的linux-manpage。为了保险起见，我并没有使用readme提供的安装教程，我是通过自己手动拷贝src文件夹下的文件成功的。
m1的brew默认安装在/opt下面，正确的做法是：
```
brew install groff
brew link groff
```
关于这一切我已经写了[详细的教程](https://zhuanlan.zhihu.com/p/349918075)在知乎上。

**Comment by hosiet** [comment]
感谢测试。我会在 #3 给出到这里的链接。

**Comment by BYRZX** [comment]
你好，我是用的是M1芯片的Mac，然后我在配置中文版man手册的时候遇到了如下问题：
未在man.conf文件中配置以下两项：
`NROFF preconv -e utf8 | /usr/local/bin/groff -Wall -mtty-char -Tutf8 -mandoc -c`
`PAGER /usr/bin/less -isR`
的时候，终端显示的man手册是有乱码的，和你知乎教程中写放的带有乱码的图片类似。
配置完上述两项之后，man查看指令手册就无法显示出内容了，只有一个`END`。
groff我也升级到了1.22版本，也按照你的教程link了，你知道该如何解决我的问题嘛？

**Comment by HoLo-Debris** [comment]
在没有配置那两项内容的时候，使用man man命令是正常的英文手册内容，没有乱码。只有使用man查看别的指令的时候显示的是乱码

**Comment by JiangWenJie** [comment]
> 在没有配置那两项内容的时候，使用man man命令是正常的英文手册内容，没有乱码。只有使用man查看别的指令的时候显示的是乱码

我也遇到了同样的问题

**Comment by minguotan** [comment]
所以现在m1安装成功，但中文显示乱码的问题，解决了吗？可以通过修改man.conf文件来解决吗

**Comment by minguotan** [comment]
> > 所以现在m1安装成功，但中文显示乱码的问题，解决了吗？可以通过修改man.conf文件来解决吗
> 
> groff方面我只修改了这两项 <img alt="iShot_2022-08-06_19 37 20" width="1001" src="https://user-images.githubusercontent.com/38827394/183247412-6cfbd33c-2a48-419e-bf83-dd91c9e73dc1.png"> 已经可以正常显示了 <img alt="iShot_2022-08-06_19 40 27" width="1015" src="https://user-images.githubusercontent.com/38827394/183247433-96e08346-d959-4171-bbb3-4f499b532a5b.png"> 不过对于你所说的乱码问题，我觉得有可能是不同终端的问题，你可以试下这个方案： `echo "export LANG=en_US.UTF-8" >> ~/.zshrc` `source ~/.zshrc`

感谢回复。
之前试过 [#3](https://github.com/man-pages-zh/manpages-zh/issues/3) 的方法来修改`/etc/man.conf`，确实会出现查看中文命令仅显示“END”的情况。修改zshrc似乎也没什么作用……

**Comment by TruElysian** [comment]
> * 机器：macbook pro m1
> * 系统版本：Big Sur 11.2
> * 效果：成功使用中文不乱码（手动copy paste同时安装最新版的groff）
>   ![v2-4255215e66c4b5791bbfa6a41b9667b4_r](https://user-images.githubusercontent.com/61637391/107150890-ff0f3980-699a-11eb-9900-a4e6e3a82ff3.jpg)
> 
> 我提出这个Issue是为了让更多的用m1的mac用户不要踩我踩过的坑，另一方面也是证明在mac上使用linux中文manpage的可行性。 我在m1芯片上的mac上成功使用了双语的linux-manpage。为了保险起见，我并没有使用readme提供的安装教程，我是通过自己手动拷贝src文件夹下的文件成功的。 m1的brew(酿造)默认安装在/opt下面，正确的做法是：
> 
> ```
> brew install groff
> brew link groff
> ```
> 
> 关于这一切我已经写了[详细的教程](https://zhuanlan.zhihu.com/p/349918075)在知乎上。

您好，知乎上的文章已经没了，并且我也没有找到存档，请问还有别的地址能访问吗？
