### ISSUE TITLE
繁體中文支援

### ISSUE THREAD

**Issue by JackKuo-tw** [man-pages-zh/manpages-zh#24]
在 Debian 上試了這個專案，發現在 zh_TW 設定上可以顯示繁體中文，不過不是台灣用語。

我看原始碼中都是 zh_CN 的語系，請問是使用什麼方式轉換的呢？

推薦人力不足的話可以使用 [OpenCC](https://github.com/BYVoid/OpenCC)，用語上可以轉成 zh_TW、zh_HK，因為同是繁體但在用語上仍有些不同。

如果有需要可以翻完發個訊息給我校對 zh_TW 用法 ：）

**Comment by hosiet** [comment]
目前转换使用的是 `s2t.json` 。我会考虑加入参数使用新版 opencc 中的 `*2tw.json`。
