### ISSUE TITLE
请问下Mac OS 可否进行安装

### ISSUE THREAD

**Issue by yangfan21** [man-pages-zh/manpages-zh#3]
如果不能安装的话 请教下Mac os如何进行恢复  现在man 无法使用了   我是按照1.5的那套折腾的

**Comment by hosiet** [comment]
为了实现更好的繁简转换，新版的构建依赖从 perl 变成了！Python3 和 opencc 1.x。请在构建（Make）前确认 Mac 系统上是否可以从 PATH 找到这些软件。

其实说到底，Mac 的工具和 GNU 的工具差太多了，现在 manpages-zh 大多数是 GNU 工具的手册页而不是 BSD 系的，手册页内容不一样，参考价值不大。但如果你仍然想要安装而且实在无法使用 Python3 和 opencc 的话，请再和我说一下，我会改进构建系统。

**Comment by yangfan21** [comment]
我的机子上已经安装了python3 和opencc1.0.4  PATH可以找到这两个，我现在的不管中文的还是英文的都不能用了  首要目标是能不能有个手册   中文英文都好说

**Comment by hosiet** [comment]
我自己没有 Mac，应该没法帮你，不过你可以把现在出问题的错误输出截图发出来看看。从我在 Linux 上的使用来看，我现在唯一的建议是重新刷新 mandb 数据库。不过 BSD 系的 man 和 GNU 的 man 区别很大，具体操作并不清楚。

**Comment by yangfan21** [comment]
首先 表示非常非常感谢，我现在使用 man ls 或者zman ls (我自己alias的) 都是一片空白  是按照 这个来的http://www.jianshu.com/p/5e35202fc59c    1.6的不知道怎么编译

**Comment by hosiet** [comment]
简略看了看，表面上没什么问题，不过自行替换 groff 的做法实在有点虚。

我个人只对 1.5.4.1 及以后的版本负责（这是我接手的版本）。

**Comment by yangfan21** [comment]
的确是这样，在安装groff之前虽然是乱码 但是还是有内容的   我如果重新安装groff试试

**Comment by yangfan21** [comment]
表示还是没办法 那1.6的这个版本在mac上使用能指导一下吗？

**Comment by hosiet** [comment]
我建议先把之前安装的影响完全消除再说。现在你的 man 能正常使用吗？如果可以正常显示英文再走下一步。1.6 的安装理论上仍然很简单，四步走 

* autoreconf --install
* ./configure
* make
* make install # 需要管理员权限

当然，放到 Mac 上我完全不知道会出啥状况。构建需要 autoconf, automake, python3, opencc 1.x.

**Comment by yangfan21** [comment]
感谢感谢  昨晚折腾了一下 终于恢复了英文的man 手册   在mac上无法按照你上面说的方式来安装中文手册，我的步骤如下：

- autoconf -i   (你应该是将单词打错了，其次参数应该是--initialization 没有install)
- ./configure 

这个时候会出现以下两个错误：
 ./configure: line 1687: syntax error near unexpected token `subdir-objects'
./configure: line 1687: `AM_INIT_AUTOMAKE(subdir-objects)'

我的构建依赖版本如下：

- autoconfig  2.69
- automake    1.15
- python3      3.6.0
- opencc       1.0.4
以上构建依赖工具都在PATH路径中，如果可以的话 还是希望能够在Mac上能够使用中文的1.6手册，万分感谢！

**Comment by hosiet** [comment]
我的确没打错，是 autoreconf，应该由 autoconf 软件提供这个工具。Mac 上真的没这玩意嘛？这是 autotools 经典的工具诶，我用的也是 autoconf 2.69 和 automake 1.15。
![man autoreconf_080](https://cloud.githubusercontent.com/assets/8443926/22720595/a6f58ce2-ede6-11e6-828d-b506e9e8504c.png)

如果 Mac 上无法识别 subdir-objects，把这个单词删掉试试看。

**Comment by hosiet** [comment]
![hosiet hosiet-tp -dev-shm-manpages-zh_081](https://cloud.githubusercontent.com/assets/8443926/22720697/4d1712f8-ede7-11e6-8ead-e80ff29a4af5.png)

**Comment by yangfan21** [comment]
的确应该是按照你的那个来，是我自作聪明了，抱歉. 编译安装应该都是成功了
安装成功后再.zshrc 中添加了一个alias zman='man -M /usr/local/share/man/zh_CN'  
但是使用zman ls后并没有转换为中文

![image](https://cloud.githubusercontent.com/assets/11313960/22720935/e0e7ace4-ede8-11e6-9b1b-d086bec62094.png)

但是看下面的手册的github地址应该就是你的这个仓库了

![image](https://cloud.githubusercontent.com/assets/11313960/22720969/126670b6-ede9-11e6-990b-2af51ca61a96.png)

**Comment by hosiet** [comment]
至少文件已安装，中文文件已可以加载，中文显示与否就是排版引擎的问题了，也许你需要新版 groff。从这里开始就帮不了你了。Linux 各发行版都会带新版 groff（例如 1.22.3，未发布的 1.22.4 也包含部分重要中文补丁）。

**Comment by iostyle** [comment]
最后解决了吗

**Comment by hosiet** [comment]
希望 Mac 用户（尤其是使用新版 Mac 系统的用户）能够继续进行测试。现在可以确定的是安装不是问题。

**Comment by liulongfei** [comment]
乱码问题我这边解决了：

1. 安装 groff
`brew install groff`

2. 编辑 `/etc/man.conf` 文件末尾加上如下语句，然后保存、退出
`NROFF preconv -e UTF8 | /usr/local/bin/nroff -Tutf8 -mandoc -c`

**Comment by lrvy** [comment]
发现个神奇的事情
sudo make install 后，查看man pages还是英文。折腾半天后注意到nmap（brew安装的）的中文man page 文件在/usr/local/share/man/zh目录，尝试cp -r /usr/local/share/man/zh_CN/* /usr/local/share/man/zh后man pages就变为中文了，好像在macOS下的中文本地化man pages的目录名应该为zh而不是zh_CN, 不知道是不是我哪里瞎改出的问题...

**Comment by snow212-cn** [comment]
> 发现个神奇的事情
> sudo make install 后，查看man pages还是英文。折腾半天后注意到nmap（brew安装的）的中文man page 文件在/usr/local/share/man/zh目录，尝试cp -r /usr/local/share/man/zh_CN/* /usr/local/share/man/zh后man pages就变为中文了，好像在macOS下的中文本地化man pages的目录名应该为zh而不是zh_CN, 不知道是不是我哪里瞎改出的问题...

估计是man参数值写错了,
`alias cman='man -M /usr/local/share/man/zh_CN'`你少了个_CN

**Comment by yi-you** [comment]
man grep 
出现以下warning，是什么原因呢？
:troff: /usr/local/share/man/zh_CN/man1/grep.1:630: warning [p 5, 8.7i]: can't break line
troff: /usr/local/share/man/zh_CN/man1/grep.1:630: warning [p 5, 9.0i]: cannot adjust line
troff: /usr/local/share/man/zh_CN/man1/grep.1:647: warning [p 5, 10.2i]: cannot adjust line
troff: /usr/local/share/man/zh_CN/man1/grep.1:647: warning [p 5, 10.3i]: can't break line
troff: /usr/local/share/man/zh_CN/man1/grep.1:652: warning [p 5, 11.0i]: can't break line
troff: /usr/local/share/man/zh_CN/man1/grep.1:669: warning [p 6, 1.0i]: can't break line

**Comment by yi-you** [comment]
> 乱码问题我这边解决了：
> 
> 1. 安装 groff
>    `brew install groff`
> 2. 编辑 `/etc/man.conf` 文件末尾加上如下语句，然后保存、退出
>    `NROFF preconv -e UTF8 | /usr/local/bin/nroff -Tutf8 -mandoc -c`

写全路径，touchbar上面的man page可以使用
NROFF /usr/local/bin/preconv -e UTF8 | /usr/local/bin/nroff -Tutf8 -mandoc -c

**Comment by hosiet** [comment]
ARM 架构的 Mac 机器具体情况请见 #22 .

**Comment by yaofei517** [comment]
举个例子  mac 的date 命令不是linux体系的  翻译文档和mac实际用法不一样啊，不知道还有哪些命令不一样

**Comment by minguotan** [comment]
> 乱码问题我这边解决了：
> 
> 1. 安装 groff
>    `brew install groff`
> 2. 编辑 `/etc/man.conf` 文件末尾加上如下语句，然后保存、退出
>    `NROFF preconv -e UTF8 | /usr/local/bin/nroff -Tutf8 -mandoc -c`

m1尝试添加，会导致man查看只显示“END”，[#22](https://github.com/man-pages-zh/manpages-zh/issues/22)自己关掉了回答并删除了知乎的解答，目前似乎还没有好的解决办法？

**Comment by bpixdb30** [comment]
这个是为啥。 所有楼层我都看了。 起步我就g了。 有没有好心人，总结一下所有情况的mac os 安装啊。 我本地python，autoreconf版本都很正常。
![image](https://github.com/man-pages-zh/manpages-zh/assets/138728087/c1522b2d-55f6-476d-b49b-e1112e7e3ea6)

**Comment by hanfengv** [comment]
work for me

cd ~/Applications
git clone https://github.com/man-pages-zh/manpages-zh.git
# 禁用繁体 option(ENABLE_ZHTW "Enable installing zh_TW man pages" OFF)
vim ./CMakeLists.txt
mkdir build && cd build/
cmake ..
make
make install
# 添加到 ~/.zshrc
alias zman='man -M /usr/local/share/man/zh_CN'

**Comment by Temsys-Shen** [comment]
我是用readme中的命令可以成功安装且没有任何显示问题，不需要安装groff
```
mkdir build && cd build/
cmake ..
make
sudo make install

cman ls
```

**Comment by TulanCN** [comment]
再更新一下，我也是使用README中的命令成功安装，没有任何问题
macOS 15.6，M3芯片

克隆仓库后进入仓库内打开终端，以下是命令：
```
brew install cmake #没安装cmake的话用brew安装，已安装则跳过
mkdir build && cd build/
cmake ..
make
sudo make install
echo "alias cman='man -M /usr/local/share/man/zh_CN'" >> ~/.zshrc
```
安装完毕后重新打开终端，测试一下：
```
cman ls
```

感谢开源社区各位的付出！

**Comment by eastLaugh** [comment]
macos 实测没有问题，需要设置 alias man='man -M /usr/local/share/man/zh_CN'
