### ISSUE TITLE
mac 上的date命令与linux不一致

### ISSUE THREAD

**Issue by kevin2027** [man-pages-zh/manpages-zh#30]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/41509375/157815891-e7f91163-768a-46ee-9254-5ca07acf936a.png">

**Comment by hosiet** [comment]
所以的确有区别，不过本项目能做些什么呢？我现在的想法是如果 Mac 下的 date 手册页是授权合理（自由软件）的文档的话，本项目可以按照衍生作品的形式进行翻译。如果授权不自由的话那翻译就不可能了。

目前我并不知道 Mac 下手册页的源码在哪里提供（Apple 是否开源，或者是否来自某个 BSD），欢迎提供更多信息。

**Comment by yaofei517** [comment]
是否通过替换 /usr/share/man目录下的手册内容中的英文单词来达到翻译的目的

**Comment by hosiet** [comment]
技术上怎么做都可以（这不是重点），我想了解的是 Mac 上 date 工具的手册页使用了什么许可证，是不是自由软件以及源码在哪里可以找到。这个问题解决之后可以另开议题讨论如何提供 Mac 版的翻译。

**Comment by yaofei517** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/41509375/157857433-7c0e69b0-b3af-4abb-b13b-0b7a55c22133.png">
看代码显示是来自FreeBSD

**Comment by hosiet** [comment]
所以这些手册页应该是 BSD-3-Clause 的许可证。如果有翻译苹果系统的 BSD 风格工具手册页的需求，可以另开 issue 讨论。
