### ISSUE TITLE
Make toolchain portable

### ISSUE THREAD

**Issue by hosiet** [man-pages-zh/manpages-zh#5]
Current build toolchain rely on GNU Make. To make things portable, we need to find a way to get rid of it by either switching to CMake or find a way to circumvent wildcard problem.

Any suggestion would be welcome.

**Comment by sadhen** [comment]
CMake比较靠谱

**Comment by hosiet** [comment]
CMake 真的没用过，Autotools 倒是玩熟了，现在倒也能满足需求。如果有啥想法不妨写个原型出来看看。

**Comment by hosiet** [comment]
closed by f1170c10185d1be9d42146e9779249bde89b2b08 .
