### ISSUE TITLE
man1/bash.1 翻译错误

### ISSUE THREAD

**Issue by rewqazxv** [man-pages-zh/manpages-zh#8]
https://github.com/man-pages-zh/manpages-zh/blob/3497b572e1f7485cc32a277413c7206a714eb587/src/man1/bash.1#L1780

此处的“非空”应当是“值为空”, 原文是:
"Use Alternate Value.  If parameter is **null or unset**, nothing is substituted, otherwise the expansion of word is substituted."
但现在的翻译是:
"Use Alternate Value(使用可选值)。如果 parameter **未定义或非空**，不会进行替换；否则将替换为 word 扩展后的值。"
表达了相反的意思, 且与上下文不一致

**Comment by hosiet** [comment]
ok，记下了，下一个版本修复
